### ISSUE TITLE
styling not applied to completed tasks when 'completed' filter is selected

### ISSUE THREAD

**Issue by DogwishX** [fac25/Week8_TestingProject_Patrick_Abby#21]
Current output:
![image](https://user-images.githubusercontent.com/53922624/178193190-457ba2bd-372e-4519-96ab-c66acb0dacb9.png)

Expected output:
![image](https://user-images.githubusercontent.com/53922624/178193254-5a376f27-0e2f-4edc-9e74-44749df52e4f.png)

**Comment by Abbbyccc** [comment]
@DogwishX work on this. thank you!

**Comment by DogwishX** [comment]
The changes under https://github.com/fac25/Week8_TestingProject_Patrick_Abby/pull/24 should resolve this issue.

An automated test has also been included to replicate the issue.

https://user-images.githubusercontent.com/53922624/178236652-86eca07f-56fa-4882-9d20-a81162ee0ad0.mp4
