### ISSUE TITLE
Avoid testing JS/DOM itself

### ISSUE THREAD

**Issue by oliverjam** [fac25/Week8_TestingProject_Patrick_Abby#28]
https://github.com/fac25/Week8_TestingProject_Patrick_Abby/blob/242513a074108e13fa79dcd972dc5e60d0afcef8/tests.js#L6-L21

The first tests you wrote are effectively checking that the browser has implemented DOM elements in JS correctly 😅. E.g. you're basically doing:

```js
const myObj = {};
myObj.name = "oli";
equal(myObj.name, "oli");
```

Assuming JS itself is not broken this should never fail.

There's nothing _wrong_ with doing this, but it's probably better to focus on testing your own code.

**Comment by DogwishX** [comment]
Hi Oli,

I believe we wrote these tests when we were creating our own `test-helper.js`  functions. These were created to test the test functions themselves, making sure the output of our helper functions were returning as expected - before working on the rest of the project. In hindsight a simple `return equal(true, true)` would have sufficed. 
Regardless of the context in which they were created, they are now obsolete and will be removed.

Thank you for bringing this to our attention.
